-- Categorias adicionais (serviços reais no Brasil). Ignora duplicata pelo UNIQUE em nome.
insert into categorias (nome) values
  ('Babá e cuidados infantis'),
  ('Cuidador de idosos'),
  ('Personal trainer'),
  ('Fotografia e vídeo'),
  ('Design gráfico'),
  ('Marketing digital'),
  ('Contabilidade e MEI'),
  ('Consultoria jurídica'),
  ('Motoboy e entregas'),
  ('Motorista aplicativo'),
  ('Chaveiro'),
  ('Serralheria e grades'),
  ('Gesso e drywall'),
  ('Impermeabilização'),
  ('Dedetização e controle de pragas'),
  ('Lavagem de estofados e carpetes'),
  ('Costura e ajustes de roupas'),
  ('Som, luz e eventos'),
  ('Buffet e cozinha para eventos'),
  ('Nutrição'),
  ('Psicologia (online ou presencial)'),
  ('Aulas particulares'),
  ('Tradução e revisão de textos'),
  ('Pet shop e banho e tosa'),
  ('Móveis planejados'),
  ('Mecânica automotiva'),
  ('Estética automotiva'),
  ('TI e suporte em informática'),
  ('Instalação de câmeras e alarmes'),
  ('Passadeira e arrumação'),
  ('Organização de ambientes'),
  ('Paisagismo'),
  ('Reforma de banheiro'),
  ('Reforma de cozinha'),
  ('Pisos e revestimentos'),
  ('Solda e manutenção industrial'),
  ('Limpeza pós-obra'),
  ('Frete e mudanças'),
  ('Montagem de equipamentos de academia'),
  ('Instalação de TV e painéis'),
  ('Automação residencial'),
  ('Cerca elétrica e interfone'),
  ('Telhados e calhas'),
  ('Demolição leve'),
  ('Forro PVC e mineral'),
  ('Instalação de ventilador de teto'),
  ('Conserto de eletrodomésticos'),
  ('Costura de cortinas'),
  ('Podologia'),
  ('Massoterapia e quiropraxia'),
  ('Cabeleireiro e barbearia'),
  ('Manicure e design de sobrancelhas'),
  ('Confeitaria e bolos sob encomenda'),
  ('Catering corporativo')
on conflict (nome) do nothing;
